# Generated by Django 5.0.6 on 2025-05-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_archive_customer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='tin',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
